runtime: python39
service: frontend
entrypoint: streamlit run app.py --server.port $PORT --server.address 0.0.0.0

# Environment variables to ensure headless operation
env_variables:
  STREAMLIT_SERVER_HEADLESS: true
  STREAMLIT_SERVER_ENABLE_CORS: false
  STREAMLIT_SERVER_PORT: $PORT
  STREAMLIT_SERVER_ADDRESS: '0.0.0.0'
  STREAMLIT_BROWSER_GATHER_USAGE_STATS: false

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2
